# Generated by Django 4.2.13 on 2024-06-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='reserved',
            field=models.BooleanField(),
        ),
    ]
