# Generated by Django 4.2.13 on 2024-06-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_alter_seat_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='FirstApp.user'),
        ),
    ]
