# Generated by Django 5.0.7 on 2024-07-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_auto_20240729_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
